services:
  email_file_saver:
    build: .
    image: hospitalposadas/email-file-worker:latest
    container_name: email_file_saver
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /mnt/Auditoria:/data
      - ./logs:/logs
    healthcheck:
      test: ["CMD", "bash", "-lc", "getent hosts $IMAP_HOST >/dev/null 2>&1 && getent hosts $SMTP_HOST >/dev/null 2>&1"]
      interval: 60s
      timeout: 5s
      retries: 5
    # dns:
    #   - 10.1.1.10
